### PR TITLE
Profile pic upload

### PR DESCRIPTION
**Pull request by ShoggyR79**
Solved a few merge conflicts and add profile image url to session
image

### CODE REVIEW

**Comment by huongthaoh** [comment]
Screenshot 2024-02-04 at 4 15 14 PM

instead of using getSignedUrl to get file from S3, can accessing file directly using bucketname + region + fileName.

**Review by JiashuHarryHuang — CHANGES_REQUESTED** [review]
Can you make upload image a **required** step for registration? Currently, if a user finishes registration, he is not able to see his profile immediately after signing up. 
image

After sign out and sign in:
image

**Comment by ShoggyR79** [comment]
> Can you make upload image a **required** step for registration? Currently, if a user finishes registration, he is not able to see his profile immediately after signing up. image
> 
> After sign out and sign in: image

image is now available in first load. Switch to pulling user data instead of pulling from session. Might be a performance impact but no work around is there since image uploading is after the initial 5 steps. 

I think you shouldnt force a user to upload an image. perhaps consider the default image route.

**Comment by JiashuHarryHuang** [comment]
> > Can you make upload image a **required** step for registration? Currently, if a user finishes registration, he is not able to see his profile immediately after signing up. image
> > After sign out and sign in: image
> 
> image is now available in first load. Switch to pulling user data instead of pulling from session. Might be a performance impact but no work around is there since image uploading is after the initial 5 steps.
> 
> I think you shouldnt force a user to upload an image. perhaps consider the default image route.

Ok I'll merge it for now and then talk to Book'em whether they want it to be a required step or not. Thanks for the good work!

**Review by JiashuHarryHuang — APPROVED** [review]
LGTM~

**Pull request merged**
